### ISSUE TITLE
Composer-Skript für Versionsnummer

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-hello-lenny#11]
Es soll ein Composer-Skript ergänzt werden, welches die Versionsnummer (dritte Ebene) automatisch hochzählt, wenn ein Commit erfolgt .
Ausserdem eine GitHub Aktion, die die versionsnummer auf 2ter Ebene hochzählt, wenn ein erfolgreicher Merge in Main erfolgt.

**Comment by xwolfde** [comment]
Hinweis:
Die Versionsnummer wird mindestens an zwei Orten geführt:

Im Hauptskript rrze-hello-lenny.php und in package.json

Der EIntrag in `package.json` ist der initiale Wert, von der die Berechnung erfolgt. Das Composer-Skript welches die Versionsnummer hochzählt, ändert die Nummer in beiden Dateien.

**Comment by thenickless** [comment]
in package.json mit npm : https://github.com/RRZE-Webteam/rrze-hello-lenny/commit/f822eacd8229156e86f7a54b912bee57b7270d18

Der Workflow muss noch auf Github eingebaut werden (increment-version.yml in .github/workflows)

```
name: Increment Version

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Increment version number
        run: npm version patch --no-git-tag-version

      - name: Update version in other files
        run: node increment-version.js

      - name: Commit version changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Incremented version to $(cat package.json | jq -r .version)"
          git push



```

Versionsnummer ist nötig in:

- package.json
- README.md
- rrze-hello-lenny.php
